# Generated by Django 4.1.7 on 2023-02-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='student_register',
        ),
    ]
