# Generated by Django 4.1.7 on 2023-05-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_student_student_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_register',
        ),
    ]
